# Seance 7

Baptiste PELLARIN - <baptiste.pellarin@cpe.fr>

## Exercice 1

In [2]:
import numpy as np

A = np.array ([ [3,1,5], [9, 8, -1], [110, 12 ,2] ])
B = np.array ([ [8, -1, 8], [2, 1, 3], [18, 2, 32] ])

C= A+B
print("A : ",A)
print("B : ",B)
print("A + B : ",C)

A :  [[  3   1   5]
 [  9   8  -1]
 [110  12   2]]
B :  [[ 8 -1  8]
 [ 2  1  3]
 [18  2 32]]
A + B :  [[ 11   0  13]
 [ 11   9   2]
 [128  14  34]]


## Exercice 2

In [3]:
import numpy as np
 
A = np.array([ [3, 1, 5], [9, 8, -1], [10, 12, 2] ])
B = np.array([ [8, -1, 8], [2, 1, 3], [18, 2, 32] ])
 
C = A.dot(B)
 
print("A : ", A)
print("B : ", B)
print("A * B : ", C)

A :  [[ 3  1  5]
 [ 9  8 -1]
 [10 12  2]]
B :  [[ 8 -1  8]
 [ 2  1  3]
 [18  2 32]]
A * B :  [[116   8 187]
 [ 70  -3  64]
 [140   6 180]]


## Exercice 3

In [5]:
def eststochastique(P):
    nl = len(P)  # nombre de lignes
    nc = len(P[0])  # nombre de colonnes
 
    etat = True  # on suppose que la matrice est stochastique
    for i in range(nl):
        s = 0
        for j in range(nc):
            s += P[i][j]
        if s > 1:
            etat = False
            break
    return etat
 
 
def estbistochastique(P):
    nl = len(P)  # nombre de lignes
    nc = len(P[0])  # nombre de colonnes
 
    etat = True  # on suppose que la matrice est bistochastique
    if(eststochastique(P)):
        for j in range(nc):
            s = 0
            for i in range(nl):
                s += P[i][j]
            if s > 1:
                etat = False
                break
    return etat
 
 
def vecteurstable(G, h):
    nl = len(G)  # nombre de lignes
    nc = len(G[0])  # nombre de colonnes
    etat = True
    if(eststochastique(G)):
        for j in range(nc):
            s = 0
            for i in range(nl):
                s += h[i]*G[i][j]
            if s != h[j]:
                etat = False
                break
    else:
        etat = False
    return etat

# Exercice 4

In [6]:
import numpy as np
 
A = np.array([ [3, 1, 5], [9, 8, -1], [24, 12, 2] ])
 
C = A.transpose()
 
print("A : ", A)
print("Transposée de A : ", C)

A :  [[ 3  1  5]
 [ 9  8 -1]
 [24 12  2]]
Transposée de A :  [[ 3  9 24]
 [ 1  8 12]
 [ 5 -1  2]]


## Exercice 5

In [11]:
import numpy as np

A = np.array([ [3, 1, 5], [9, 8, -1], [24, 12, 2] ])
perm = np.array([ [3, 1, 5], [9, 8, -1], [24, 12, 2] ])

def apply_permutation(A,perm,N):
    B=np.empty_like(A)
    for i in range(N):
            B[A[:]==i]=perm[i]
    return B

ValueError: NumPy boolean array indexing assignment cannot assign 3 input values to the 0 output values where the mask is true